# Utiliser une image Nginx de base
FROM nginx:latest

# Exposer le port 80 (le port par défaut pour HTTP)
EXPOSE 80

# CMD peut être utilisé pour spécifier la commande de démarrage du conteneur
CMD ["nginx", "-g", "daemon off;"]

